image: docker:stable

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u lisboalien -p 8291Docker

build-docker:
  stage: build
  script:
    - docker build -t minha-imagem .
