image: docker:stable

stages:
  - pre-build
  - build
  - test
  - deploy

services:
  - docker:dind

before_script:
  - docker info
  - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin

build-docker:
  stage: pre-build
  script:
    - docker build -t minha-imagem .
    - docker tag minha-imagem lisboalien/minha-imagem:latest
    - docker push lisboalien/minha-imagem:latest

build_project:
  stage: build
  tags:
    - task-executor
  dependencies:
    - build-docker
  script:
    - echo "runner"
