image: docker:stable

services:
  - docker:dind

bofore_script:
  script:
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build-docker:
  stage: build
  script:
    - docker build -t minha-imagem .
