image: docker:stable

services:
  - docker:dind

before_script:
  - docker info
  - echo "$CI_REGISTRY_USER"
  - echo "$CI_REGISTRY_PASSWORD"
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"

build-docker:
  stage: build
  script:
    - docker build -t minha-imagem .
