image: docker:stable

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -password-stdin < ~/my_password

build-docker:
  stage: build
  script:
    - docker build -t minha-imagem .
